sitemoguena/meters/urls.py
from django.urls import path
from . import views

# П А К Е Т    П Р И Л О Ж Е Н И Я  meters

app_name = "meters"

urlpatterns = [
    path( '', views.MetersHome.as_view(),   name='home' ),

    path('address/<int:addr_id>/', views.address, name='address'),

    path('electro/<slug:addr_slug>/', views.ShowElectro.as_view(), name='electro'),
    path('water/<slug:addr_slug>/', views.ShowWater.as_view(), name='water'),

    path('itemelectro/<slug:eitem_slug>/', views.ItemElectro.as_view(), name='item_electro'),
    path('itemwater/<slug:witem_slug>/', views.ItemWater.as_view(), name='item_water'),

    path('addelectro/<slug:address_slug>/', views.AddElectro.as_view(), name='add_electro'),
    path('addelectroDayly/<slug:address_slug>/', views.AddElectroDayly.as_view(), name='add_electro_dayly'),
    path('newelectro/<slug:address_slug>/', views.NewElectro.as_view(), name='new_electro'),

    path('addwater/<slug:address_slug>/', views.AddWater.as_view(), name='add_water'),
    path('newwater/<slug:address_slug>/', views.NewWater.as_view(), name='new_water'),

    path('selector/<slug:type_meters>/<slug:addr_slug>/', views.SelectorService.as_view(), name='selector'),

    path('about/', views.about, name='about'),
    path('login/', views.login, name='login'),

    path('contact/', views.ContactFormView.as_view(), name='contact'),
]

sitemoguena/meters/templates/meters/about.html
{% extends 'meters/base.html' %}

{% block content %}
<h1>{{title}}</h1>
{% endblock %}

sitemoguena/meters/templates/meters/add_electro.html
{% extends 'meters/base.html' %}

{% block content %}

<h1>{{title}}</h1>
<h2> Электроэнергия</h2>
Адрес: {{address_name}} <br>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Добавить</button></p>
</form>

{% endblock %}

sitemoguena/meters/templates/meters/add_water.html
{% extends 'meters/base.html' %}

{% block content %}

<h1>{{title}}</h1>
<h2> Водоснабжение </h2>
Адрес: {{address_name}}<br>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p>
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Добавить</button></p>
</form>

{% endblock %}

sitemoguena/meters/templates/meters/address.html
{% extends 'meters/base.html' %}

{% block content %}
    address


{% endblock %}

sitemoguena/meters/templates/meters/base.html
{% load static %}
{% load meters_tags %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'meters/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'mainapp/images/main.ico' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
    <tr>
		<td valign=top>

            {%  show_menu mainmenu  address_slug user %}

            <table border=0 cellpadding="0" cellspacing="0">
                <tr>
                    <!-- Левый   столбец:  Тек дата  -->
                    <td valign="top" class="left-chapters">
                        <div class="address">
                            <br>Сегодня:<br>
                            <span class="text-accent">{{ curdatetxt }}</span>
                            <br>
                        </div>
                    </td>
                    <!-- Правый   столбец  Основные данные -->
                    <td valign="top" class="content">
                        <div class="content-text">

                            {% block vibaddress %}
                            {% endblock %}

                            {% block content %}
                            {% endblock %}
                        </div>
                        {% block navigation %}
					    {% endblock %}
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>
</html>

sitemoguena/meters/templates/meters/choice_address.html
<form action="{% url 'home' %}" method="post" >
    {% csrf_token %}

    {% for f in form_address %}
        <p>
        <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
        {{ f }}
        </p>
    {% endfor %}
    <p> <label>Потребление:</label>
    <p> <button type="submit" name='choice_btn' value='water'> Вода </button>
    <p> <button type="submit" name='choice_btn' value='electro'> Электричество </button>
</form>

sitemoguena/meters/templates/meters/contact.html
{% extends 'meters/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>
            {{ f }}
        </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Отправить</button>
</form>

{% endblock %}

sitemoguena/meters/templates/meters/e_indication.html
{% extends 'meters/base.html' %}

{% block content %}
        {{indication.date_reading}} <br>
        Тариф: {{indication.tar.name}} <br>
        Адрес: {{address_name}} <br>
        Автор: {{indication.author.username|default:'неизвестен'}} <br>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" >Сохранить</button>
        </form>

{% endblock %}

sitemoguena/meters/templates/meters/electro.html
{% extends 'meters/base.html' %}

{% block content %}
    <h2> Электроэнергия</h2>

    Адрес: {{ address_name }} <br>
    {% if indication|length > 0%}
        Тариф: {{indication.0.tar.name}}
    {% else %}
        Тариф: не определен
    {% endif %}
     <br><br>

    {% if indication|length > 0 %}
        {% if indication.0.tar.number > 1 %}
            <a href="{% url  'meters:add_electro'  address_slug %}">Добавить показание</a>
        {% else %}
            <a href="{% url  'meters:add_electro_dayly'  address_slug %}">Добавить показание</a>
        {% endif %}
    {% else %}
        <a href="{% url  'meters:new_electro'  address_slug %}">Создать показание</a>
    {% endif %}
    <br>

    <table class="table-meters">

    {% if indication|length > 0%}
        <th>Снято</th>
        {% if indication.0.tar.number == 1 %}
            <th>сутки</th>
            <th>ИзмСутки </th>
        {% else %}
            <th>День</th>
            <th>Ночь</th>
            <th>ИзмДень </th>
            <th>ИзмНочь </th>
        {% endif %}

    {% else %}
        <th>Снято</th>
        <th>сутки</th>
        <th>День</th>
        <th>Ночь</th>
        <th>ИзмСутки </th>
        <th>ИзмДень </th>
        <th>ИзмНочь </th>
    {% endif %}

    {% if indication|length > 0%}
        {% for tr in indication %}
            <tr >
                <td> <a href="{{ tr.get_absolute_url }}">{{tr.date_reading}} </a></td>
                {% if indication.0.tar.number == 1 %}
                    <td> {{tr.dayly}} </td>
                    <td>
                        {% if tr.difference %}
                            {{ tr.difference.dayly }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                {% else %}
                    <td> {{tr.daytime}} </td>
                    <td> {{tr.nighttime}} </td>
                    <td>
                        {% if tr.difference %}
                            {{ tr.difference.daytime }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    <td>
                        {% if tr.difference %}
                            {{ tr.difference.nighttime }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    {% endif %}
    </table>


{% endblock %}

sitemoguena/meters/templates/meters/index.html
{% extends 'meters/base.html' %}

{% block vibaddress %}

{% endblock %}

{% block content %}
    <label> Адрес:</label>
    <label> {{address_name}}</label>
{% endblock %}

sitemoguena/meters/templates/meters/show_menu.html
<div class="header">
    <ul id="mainmenu" class="mainmenu">
        {% for m in menu %}
            {% if m.url_name == 'submenu' %}
                <li class="dropdown">
            {% else %}
                <li>
            {% endif %}
            {% if m.url_name != 'submenu' %}
                <a href="{% url m.url_name %}">{{m.title}}</a>
            {% else %}
                {% if m.title == 'Адрес' %}
                    <a href="#">{{m.title}}</a>
                    <ul class="submenu">
                        <!-- {'title': f'{v.city}, {v.street}',   'id':v.pk, 'slug':v.slug } -->
                        {% for v in m.submenu %}
                            <li><a href="{% url  'meters:address'  v.id  %}">{{v.title}}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% if m.title == 'Показания' %}
                    <a href="#">{{m.title}}</a>
                    <ul class="submenu">
                        <!-- {'title': f'{v.city}, {v.street}',   'id':v.pk, 'slug':v.slug } -->
                        {% for v in m.submenu %}
                            {% if address_slug %}
                                <li><a href="{% url  v.type  address_slug  %}">{{v.title}}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endif %}
            </li>
        {% endfor %}

        {% if user_id.is_authenticated %}
            <li class="last">
                <a href="{% url 'users:profile' %}">{{user_id.username}} </a> |
                    <a href="{% url 'users:logout' %}">Выйти</a></li>
        {% else %}
            <li class="last">
                <a href="{% url 'users:login' %}">Войти</a> |
                <a href="{% url 'users:register' %}">Регистрация</a></li>
        {% endif %}
        <div class="clear"></div>

    </ul>
</div>

sitemoguena/meters/templates/meters/w_indication.html
{% extends 'meters/base.html' %}

{% block content %}
        {{indication.date_reading}} <br>
        Адрес: {{address_name}} <br>
        Автор: {{indication.author.username|default:'неизвестен'}} <br>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" >Сохранить</button>
        </form>

{% endblock %}

sitemoguena/meters/templates/meters/water.html
{% extends 'meters/base.html' %}

{% block content %}
    <h2> Водоснабжение </h2>

    Сегодня: {{curdatetxt}} <br>
    Адрес: {{ address_name }} <br><br>

    {% if indication|length > 0 %}
        <a href="{% url  'meters:add_water'  address_slug %}">Добавить показание</a>
    {% else %}
        <a href="{% url  'meters:new_water'  address_slug %}">Создать показание</a>
    {% endif %}
    <br>

    <table class="table-meters">
    <th>Снято</th>
    <th>Горячая</th>
    <th>Холодная</th>
    <th>ИзмГВС </th>
    <th>ИзмХВС </th>

    {% for tr in indication %}
        <tr >
            <td> <a href="{{ tr.get_absolute_url }}">{{tr.date_reading}} </a></td>
            <td> {{tr.hot}} </td>
            <td> {{tr.cold}} </td>
            <td>
                {% if tr.difference %}
                    {{ tr.difference.hot }}
                {% else %}
                    -
                {% endif %}
            </td>
            <td>
                {% if tr.difference %}
                    {{ tr.difference.cold }}
                {% else %}
                    -
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>


{% endblock %}